### ISSUE TITLE
Hello, let's talk about the KF2 ranked

### ISSUE THREAD

**Issue by YCCCCCCCCC** [Ruuv1337/KF2Connector#2]
Hello, I'm sorry to bother you, but I saw your project (Any mutator on server is always in RANKED status) on github and it doesn't open 404, can you share it with me? My KF2 server is currently using some Mutators causing the server to be unranked.I would be very grateful for your help!😄

**Comment by Ruuv1337** [comment]
If price of $100 doesn't scare you, i waiting in discord.
Discord: [object Object]#6990
